# Generated by Django 2.2.25 on 2021-12-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211209_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='c_date',
            new_name='created_date',
        ),
    ]
